apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - path: replica_count.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment
