name: Run Unit Test via Pytest

on:
  push:
    paths:
      - 'app.py'  # 只有 Python 檔案的修改會觸發 workflows
    tags:
      - 'v*'      # 打上tag會觸發 workflows

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install pytest
        run: python -m pip install pytest

      - name: Install coverage
        run: python -m pip install coverage

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py310 .
        continue-on-error: true

      - name: Test with coverage and pytest
        run: coverage run -m pytest -v -s

      - name: Generate Coverage Report
        run: coverage report -m
